# Generated by Django 4.1.1 on 2022-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                ("deal", models.IntegerField()),
                ("free", models.IntegerField()),
                ("mrp", models.FloatField()),
                ("rate", models.FloatField()),
                ("exp", models.DateField()),
                ("company", models.CharField(max_length=100)),
                ("supplier", models.CharField(max_length=100)),
            ],
        ),
    ]
