# Generated by Django 4.1.1 on 2022-09-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Species", new_name="Inventory",),
    ]
